// <auto-generated />
namespace GestorInventarioEmpresas.BackEnd.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SegundaMigracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SegundaMigracion));
        
        string IMigrationMetadata.Id
        {
            get { return "201807031903386_Segunda Migracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
