// <auto-generated />
namespace GestorInventarioEmpresas.BackEnd.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _7ta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_7ta));
        
        string IMigrationMetadata.Id
        {
            get { return "201807091519254_7}ta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
