// <auto-generated />
namespace GestorInventarioEmpresas.BackEnd.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class x22ok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(x22ok));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131827234_x22ok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
